linters:
  enable:
    - dogsled
    - dupl
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - stylecheck
    - unconvert
    - unparam
    - whitespace
issues:
  exclude-rules:
    - path: glip/glip_client_commonchat_webhook.go
      text: "ineffectual assignment to glipmsg"
    - path: slack/slack_client_commonchat_webhook.go
      text: "ineffectual assignment to slackmsg"
    - path: slack/slack_client_commonchat_webhook.go
      text: "argument slackmsg is overwritten before first use"
